version: "3.8"

services:
    # MongoDB 5.0.1
    mongodb:
        container_name: mongodb
        image: mongo:5.0.1
        restart: always
        env_file: 
            - ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
            - ./conf/mongodb/scripts/:/docker-entrypoint-initdb.d/
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3
        networks: 
            - mongodb_network


    # Mongo Express
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongodb
        restart: always
        ports:
            - "8081:8081"
        env_file: 
            - ./.env
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_ADMIN_USER}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_ADMIN_PASSWORD}
        healthcheck:
            test:  wget --quiet --tries=3 --spider http://${MONGO_EXPRESS_ADMIN_USER}:${MONGO_EXPRESS_ADMIN_PASSWORD}3@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        networks: 
            - mongodb_network

    ledn-api:
        container_name: ledn-api
        depends_on:
            - mongodb
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        command: ["pm2-runtime","start","process.json","--name","ledn_server_prod"]
        env_file:
            - ./.env
        environment:
            - PORT=${LEDN_PORT}
            - LEDN_MONGO_USER=${LEDN_MONGO_USER}
            - LEDN_MONGO_PASSWORD=${LEDN_MONGO_PASSWORD}
            - LEDN_MONGO_HOSTNAME=${LEDN_MONGO_HOSTNAME}
            - LEDN_MONGO_PORT=${LEDN_MONGO_PORT}
            - LEDN_MONGO_DB=${MONGO_INITDB_DATABASE}
        ports:
            - "3000:3000"
        networks: 
            - mongodb_network
        
  
volumes:
    mongodb_data:
        driver: local
networks: 
    mongodb_network:
        name: mongodb_network