version: "3.8"

services:
    mongodb:
        container_name: mongodb
        image: mongo:5.0.1
        restart: unless-stopped
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=temppass
        ports:
            - "27017:27017"
        volumes:
            - 'mongodb_data:/data/db'
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3
        networks: 
            - mongodb_network



    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongodb
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=temppass
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        healthcheck:
            test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        networks: 
            - mongodb_network

    # server:
    #     image: node:16-alpine3.11
    #     working_dir: './server/dist'
    #     ports:
    #         - "3000:3000"
    #     volumes: 
    #         - './server/dist:/opt/'
    #     command: ''
  
volumes:
    mongodb_data:
        driver: local
networks: 
    mongodb_network:
        name: mongodb_network