version: "3.8"

services:
    # MongoDB 5.0.1
    mongodb:
        container_name: mongodb
        image: mongo:5.0.1
        restart: always
        env_file: 
            - ./.env
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
            - ./conf/mongodb/scripts/:/docker-entrypoint-initdb.d/
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3
        networks: 
            - mongodb_network


    # Mongo Express
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongodb
        restart: always
        ports:
            - 8081:8081
        env_file: 
            - ./.env
        healthcheck:
            test:  wget --quiet --tries=3 --spider http://${ME_CONFIG_MONGODB_AUTH_USERNAME}:${ME_CONFIG_MONGODB_AUTH_PASSWORD}3@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        networks: 
            - mongodb_network

    # ledn-api:
    #     container_name: ledn-api
    #     depends_on:
    #         - mongodb
    #     restart: always
    #     build:
    #         context: ./server
    #         dockerfile: .
    #     ports:
    #         - 3000:3000
    #     command: ["pm2-runtime", "start", "process.json", "--only", "ledn_server_dev", "--env","development"]
    #     networks:
    #         - mongodb_network
        
  
volumes:
    mongodb_data:
        driver: local
networks: 
    mongodb_network:
        name: mongodb_network